module Bits
  def bit(index, value) = set_flags(value & (1 << index) == (1 << index), 0, 1, nil)

  def bit_0_a() = bit(0, @a)
  def bit_0_b() = bit(0, @b)
  def bit_0_c() = bit(0, @c)
  def bit_0_d() = bit(0, @d)
  def bit_0_e() = bit(0, @e)
  def bit_0_h() = bit(0, @h)
  def bit_0_l() = bit(0, @l)

  def bit_1_a() = bit(1, @a)
  def bit_1_b() = bit(1, @b)
  def bit_1_c() = bit(1, @c)
  def bit_1_d() = bit(1, @d)
  def bit_1_e() = bit(1, @e)
  def bit_1_h() = bit(1, @h)
  def bit_1_l() = bit(1, @l)

  def bit_2_a() = bit(2, @a)
  def bit_2_b() = bit(2, @b)
  def bit_2_c() = bit(2, @c)
  def bit_2_d() = bit(2, @d)
  def bit_2_e() = bit(2, @e)
  def bit_2_h() = bit(2, @h)
  def bit_2_l() = bit(2, @l)

  def bit_3_a() = bit(3, @a)
  def bit_3_b() = bit(3, @b)
  def bit_3_c() = bit(3, @c)
  def bit_3_d() = bit(3, @d)
  def bit_3_e() = bit(3, @e)
  def bit_3_h() = bit(3, @h)
  def bit_3_l() = bit(3, @l)

  def bit_4_a() = bit(4, @a)
  def bit_4_b() = bit(4, @b)
  def bit_4_c() = bit(4, @c)
  def bit_4_d() = bit(4, @d)
  def bit_4_e() = bit(4, @e)
  def bit_4_h() = bit(4, @h)
  def bit_4_l() = bit(4, @l)

  def bit_5_a() = bit(5, @a)
  def bit_5_b() = bit(5, @b)
  def bit_5_c() = bit(5, @c)
  def bit_5_d() = bit(5, @d)
  def bit_5_e() = bit(5, @e)
  def bit_5_h() = bit(5, @h)
  def bit_5_l() = bit(5, @l)

  def bit_6_a() = bit(6, @a)
  def bit_6_b() = bit(6, @b)
  def bit_6_c() = bit(6, @c)
  def bit_6_d() = bit(6, @d)
  def bit_6_e() = bit(6, @e)
  def bit_6_h() = bit(6, @h)
  def bit_6_l() = bit(6, @l)

  def bit_7_a() = bit(7, @a)
  def bit_7_b() = bit(7, @b)
  def bit_7_c() = bit(7, @c)
  def bit_7_d() = bit(7, @d)
  def bit_7_e() = bit(7, @e)
  def bit_7_h() = bit(7, @h)
  def bit_7_l() = bit(7, @l)

  def bit_0_a_hl() = bit(0, read_byte(hl))
  def bit_1_a_hl() = bit(1, read_byte(hl))
  def bit_2_a_hl() = bit(2, read_byte(hl))
  def bit_3_a_hl() = bit(3, read_byte(hl))
  def bit_4_a_hl() = bit(4, read_byte(hl))
  def bit_5_a_hl() = bit(5, read_byte(hl))
  def bit_6_a_hl() = bit(6, read_byte(hl))
  def bit_7_a_hl() = bit(7, read_byte(hl))
end
